<!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        body{
            fmargin: 0;
            padding: 0;
            font-family: "Open Sans", sans-serif !important;
            line-height: 1.6;
        }
    </style>
</head>
<body>
    <div class="container">
        <span>Good Day!</span>
        <br>
        <span>You are making a verification for iShare System.</span>
        <br>
        <span>Your OTP Code is <strong style="text-decoration: underline;">{{ $otpCode }}</strong> DO NOT SHARE WITH ANYONE.</span>
        <br>
        <br>
        <i>Disclaimer: This notification is automatically generated by the iShare System.</i>
    </div>
</body>
</html>